const itineraryData = [
  {
    id: "row-2",
    sourceRow: 2,
    city: "VUELO IDA Y VUELTA",
    date: "2026-08-14",
    departureTime: "17:50",
    departurePlace: "Buenos Aires",
    arrivalTime: "10:45",
    arrivalPlace: "Madrid",
    country: "España",
    category: "VUELO",
    usd: 3020.2,
    payer: "FLOR",
    status: "PAGO",
    locked: true,
    note: "Vuelo internacional confirmado."
  },
  {
    id: "row-3",
    sourceRow: 3,
    city: "PARIS",
    date: "2026-08-15",
    departureTime: "15:45",
    departurePlace: "Madrid",
    arrivalTime: "17:55",
    arrivalPlace: "Paris",
    country: "Francia",
    category: "VUELO INTERNO",
    usd: 401.8,
    payer: "GON",
    status: "PAGO",
    locked: true,
    note: "Vuelo interno confirmado."
  },
  {
    id: "row-4",
    sourceRow: 4,
    city: "PARIS",
    date: "2026-08-16",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "ESTADIA",
    usd: 500,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-5",
    sourceRow: 5,
    city: "PARIS",
    date: "2026-08-17",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMIDA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-6",
    sourceRow: 6,
    city: "PARIS",
    date: "2026-08-18",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "DISNEY",
    usd: 200,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: "Flexible: puede moverse dentro de Paris, por ejemplo al 17."
  },
  {
    id: "row-7",
    sourceRow: 7,
    city: "LONDRES",
    date: "2026-08-19",
    departureTime: "10:01",
    departurePlace: "Paris",
    arrivalTime: "11:30",
    arrivalPlace: "Londres",
    country: "Reino Unido",
    category: "TREN",
    usd: 147.42,
    payer: "FLOR",
    status: "PAGO",
    locked: true,
    note: "Tren confirmado."
  },
  {
    id: "row-8",
    sourceRow: 8,
    city: "LONDRES",
    date: "2026-08-20",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "ESTADIA",
    usd: 600,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-9",
    sourceRow: 9,
    city: "LONDRES",
    date: "2026-08-21",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMIDA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-10",
    sourceRow: 10,
    city: "LONDRES",
    date: "2026-08-22",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "ETA",
    usd: 56.34,
    payer: "FLOR",
    status: "PAGO",
    locked: true,
    note: "ETA confirmada."
  },
  {
    id: "row-11",
    sourceRow: 11,
    city: "AMSTERDAM",
    date: "2026-08-23",
    departureTime: "11:45",
    departurePlace: "Londres",
    arrivalTime: "14:05",
    arrivalPlace: "Amsterdam",
    country: "Paises Bajos",
    category: "VUELO INTERNO",
    usd: 228.4,
    payer: "GON",
    status: "PAGO",
    locked: true,
    note: "Vuelo interno confirmado."
  },
  {
    id: "row-12",
    sourceRow: 12,
    city: "AMSTERDAM",
    date: "2026-08-24",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "ESTADIA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-13",
    sourceRow: 13,
    city: "AMSTERDAM",
    date: "2026-08-25",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMIDA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-14",
    sourceRow: 14,
    city: "AMSTERDAM",
    date: "2026-08-26",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "",
    usd: null,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: "Día disponible para completar."
  },
  {
    id: "row-15",
    sourceRow: 15,
    city: "ESTAMBUL",
    date: "2026-08-27",
    departureTime: "12:40",
    departurePlace: "Amsterdam",
    arrivalTime: "17:05",
    arrivalPlace: "Estambul",
    country: "Turquia",
    category: "VUELO INTERNO",
    usd: 244,
    payer: "GON",
    status: "PAGO",
    locked: true,
    note: "Vuelo interno confirmado."
  },
  {
    id: "row-16",
    sourceRow: 16,
    city: "ESTAMBUL",
    date: "2026-08-28",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "ESTADIA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-17",
    sourceRow: 17,
    city: "ESTAMBUL",
    date: "2026-08-29",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMIDA",
    usd: 300,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-18",
    sourceRow: 18,
    city: "ESTAMBUL",
    date: "2026-08-30",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMIDA",
    usd: 300,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-19",
    sourceRow: 19,
    city: "BARCELONA",
    date: "2026-08-31",
    departureTime: "10:10",
    departurePlace: "Estambul",
    arrivalTime: "12:50",
    arrivalPlace: "Barcelona",
    country: "España",
    category: "VUELO INTERNO",
    usd: 610.18,
    payer: "GON",
    status: "PAGO",
    locked: true,
    note: "Vuelo interno confirmado."
  },
  {
    id: "row-20",
    sourceRow: 20,
    city: "BARCELONA",
    date: "2026-09-01",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMIDA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-21",
    sourceRow: 21,
    city: "BARCELONA",
    date: "2026-09-02",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "ESTADIA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-22",
    sourceRow: 22,
    city: "MADRID",
    date: "2026-09-03",
    departureTime: "",
    departurePlace: "Barcelona",
    arrivalTime: "",
    arrivalPlace: "Madrid",
    country: "España",
    category: "TREN",
    usd: null,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: "Barcelona a Madrid pendiente de definir."
  },
  {
    id: "row-23",
    sourceRow: 23,
    city: "MADRID",
    date: "2026-09-04",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "ESTADIA",
    usd: 400,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-24",
    sourceRow: 24,
    city: "MADRID",
    date: "2026-09-05",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMIDA",
    usd: 500,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-25",
    sourceRow: 25,
    city: "MADRID",
    date: "2026-09-06",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "COMPRAS",
    usd: 2000,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: ""
  },
  {
    id: "row-26",
    sourceRow: 26,
    city: "MADRID",
    date: "2026-09-07",
    departureTime: "",
    departurePlace: "",
    arrivalTime: "",
    arrivalPlace: "",
    country: "",
    category: "",
    usd: null,
    payer: "",
    status: "PENDIENTE",
    locked: false,
    note: "Día disponible para completar."
  },
  {
    id: "row-27",
    sourceRow: 27,
    city: "VUELO IDA Y VUELTA",
    date: "2026-09-08",
    departureTime: "00:05",
    departurePlace: "Madrid",
    arrivalTime: "07:40",
    arrivalPlace: "Buenos Aires",
    country: "",
    category: "VUELO",
    usd: 0,
    payer: "",
    status: "PAGO",
    locked: true,
    note: "Tramo de vuelta incluido en vuelo internacional."
  }
];

const sourceColumns = [
  "CIUDAD",
  "Fecha",
  "Hora salida",
  "Lugar de salida",
  "Hora llegada",
  "Lugar de llegada",
  "País",
  "CATEGORIA",
  "USD",
  "PAGO",
  "ESTADO"
];
